Wishlist/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')), # 富文本编辑器
    url(r'^user/', include(('user.urls', 'user'), namespace='user')),  # 用户模块
    url(r'^group/', include(('group.urls', 'group'), namespace='group')),  # 组模块
    url(r'^wish/', include(('wish.urls', 'wish'), namespace='wish')),  # 愿望模块
]

apps/group/urls.py
from django.conf.urls import url
from group.views import GroupView, GroupUserView
urlpatterns = [

    url(r'^group$', GroupView.as_view(), name='group'),  # 分组
    url(r'^user', GroupUserView.as_view(), name='user'),  # 分组用户
]

app_name = "group"

apps/user/urls.py
from django.conf.urls import url
# from user import views
from user.views import RegisterView, LoginView, LogoutView
from user import views

urlpatterns = [
    url(r'^register$', RegisterView.as_view(), name='register'),
    url(r'^login$', LoginView.as_view(), name='login'),
    url(r'^logout$', LogoutView.as_view(), name='logout'),
    url(r'^img_upload/$', views.img_upload, name="img_upload"),
    url(r'^img_handle/$', views.img_handle, name="img_handle"),
]

app_name = "user"

apps/wish/urls.py
from django.conf.urls import url
from wish.views import WishView

urlpatterns = [

    url(r'^wish$', WishView.as_view(), name='wish'),  # 愿望列表
]

app_name = "wish"

apps/group/models.py
from django.db import models
from db.base_model import BaseModel
from user.models import User


class Group(BaseModel):

    '''分组模型类'''

    name = models.CharField(max_length=20, verbose_name='分组名称')
    create_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='创建者')
    desc = models.CharField(max_length=256, verbose_name='分组简介')
    image = models.ImageField(upload_to='group', verbose_name='分组图片')

    class Meta:
        db_table = 'wl_group'
        verbose_name = '分组'
        verbose_name_plural = verbose_name


class GroupUser(BaseModel):

    '''分组用户模型类'''

    status_choices = (
        (0, '已加入'),
        (1, '被移除'),
    )
    group = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name='所属组')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='组内用户')
    status = models.SmallIntegerField(default=0, choices=status_choices, verbose_name='用户状态')

    class Meta:
        db_table = 'wl_group_user'
        verbose_name = '分组用户'
        verbose_name_plural = verbose_name

apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from db.base_model import BaseModel
# Create your models here.


class User(AbstractUser, BaseModel):
    '''用户模型类'''

    class Meta:
        db_table = 'wl_user'
        verbose_name = '用户'
        verbose_name_plural = verbose_name

apps/wish/models.py
from django.db import models
from db.base_model import BaseModel
from group.models import Group
from user.models import User


class Wish(BaseModel):

    status_choices = (
        (0, "待抽取"),
        (1, "待完成"),
        (2, "已完成"),
        (3, "已取消"),
    )
    name = models.CharField(max_length=20, verbose_name='愿望名称')
    desc = models.CharField(max_length=256, verbose_name='愿望详情')
    group = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name='所属分组')
    create_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='创建者')
    value = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='愿望价值')
    weight = models.SmallIntegerField(default=1, verbose_name="愿望权重")
    status = models.SmallIntegerField(default=0, choices=status_choices, verbose_name='愿望状态')
    end_time = models.DateTimeField(verbose_name='截止时间')

    class Meta:
        db_table = 'wl_wish'
        verbose_name = '愿望'
        verbose_name_plural = verbose_name

apps/group/views.py
from django.shortcuts import render
from django.views.generic import View
# Create your views here.


class GroupView(View):

    def get(self, request):

        context = {
            "page": "group"
        }
        return render(request, 'group.html', context)


class GroupUserView(View):

    def get(self, request):

        context = {
            "page": "group"
        }
        return render(request, 'group_user.html', context)

apps/user/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import View
from django.http import HttpResponse

from user.models import User
from utils.fdfs.storage import FDFSStorage

# Create your views here.
from django.contrib.auth.hashers import check_password, make_password
import re


def img_upload(request):
    return render(request, 'img_upload.html')


def img_handle(request):
    f1 = request.FILES.get('img')
    fdfs = FDFSStorage()
    return HttpResponse(fdfs.save(f1.name, f1))

class RegisterView(View):

    def get(self, request):

        return render(request, 'register.html')

    def post(self, request):

        user_name = request.POST.get("user_name")
        password = request.POST.get("pwd")
        email = request.POST.get("email")

        if not all([user_name, password, email]):
            return render(request, 'register.html', {'errmsg': '数据不完整'})

        if not re.match(r'^[a-z0-9][\w.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$', email):
            return render(request, 'register.html', {'errmsg': '邮箱格式不正确'})

        try:
            user = User.objects.get(username=user_name)
        except User.DoesNotExist:
            user = None

        if user:
            return render(request, 'register.html', {'errmsg': '用户名已存在'})

        # 直接注册成功不发送验证邮件信息，后期有需求再做
        user = User.objects.create_user(user_name, password, email)
        user.password = make_password(password)
        user.is_active = 1
        user.save()

        return redirect(reverse('group:group'))


class LoginView(View):

    def get(self, request):

        return render(request, 'login.html')


class LogoutView(View):

    def get(self, request):
        pass

apps/wish/views.py
from django.shortcuts import render
from django.views.generic import View
# Create your views here.

class WishView(View):

    def get(self, request):

        context = {
            "page": "wish"
        }
        return render(request, 'wish.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}{% endblock title %}</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    {% block topfiles %}{% endblock topfiles %}
</head>
<body>
{% block header_con %}
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">菜单</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">设置</a></li>
                </ul>
                <form class="navbar-form navbar-right">
                    <input type="text" class="form-control" placeholder="搜索...">
                </form>
            </div>
        </div>
    </nav>
{% endblock header_con %}

{% block body %}
{% endblock body %}
{% block bottom_files %}
    <script src="{% static "js/jquery-1.12.4.min.js" %}"></script>
    <script src={% static "js/bootstrap.min.js" %}></script>
{% endblock bottom_files %}
</body>
</html>

templates/base_menu.html
{% extends "base.html" %}

{% block title %}愿望清单{% endblock title %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">
                    <li {% if page == 'group' %}class="active"{% endif %}><a href="{% url "group:group" %}">分组</a></li>
                </ul>
                <ul class="nav nav-sidebar">
                    <li {% if page == 'wish' %}class="active"{% endif %}><a href="{% url "wish:wish" %}">愿望</a></li>
                </ul>
            </div>
        </div>
    </div>
    {% block right_content %}{% endblock right_content %}
{% endblock body %}

templates/group.html
{% extends "base_menu.html" %}

{% block title %}愿望清单{% endblock title %}

{% block right_content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">分组</h1>

        <h2 class="sub-header">分组列表</h2>
        <button type="button" class="btn btn-primary">添加分组</button>
        {% if groups %}
            {% for group in groups %}
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>组名</th>
                            <th>简介</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td><a href="{% url "group:user" %}">哈哈哈</a></td>
                            <td>呵呵呵</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            {% endfor %}
        {% else %}
            <div>暂无分组</div>
        {% endif %}
    </div>
{% endblock right_content %}

templates/group_user.html
{% extends "base_menu.html" %}

{% block title %}愿望清单{% endblock title %}

{% block right_content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">分组名称</h1>

        <h2 class="sub-header">分组成员</h2>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>姓名</th>
                    <th>已有愿望</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>呃呃呃</td>
                    <td>22</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock right_content %}

templates/img_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>自定义上传图片</title>
</head>
<body>
<form method="post" action="{% url "user:img_handle" %}" enctype="multipart/form-data">
    {%csrf_token%}
    <input type="file" name="img"/><br>
    <input type="submit" value="上传">
</form>
</body>
</html>

templates/login.html
{% extends "base.html" %}

{% block title %}愿望清单-登陆{% endblock title %}

{% block header_con %}
{% endblock header_con %}
{% block body %}
    <div class="container">
        <form class="form-signin">
            <h2 class="form-signin-heading">用户登陆</h2>
            <label for="inputEmail" class="sr-only">请输入账号</label>
            <input type="text" id="inputEmail" class="form-control" placeholder="请输入账号" required autofocus>
            <label for="inputPassword" class="sr-only">请输入密码</label>
            <input type="password" id="inputPassword" class="form-control" placeholder="请输入密码" required>
            <div class="checkbox">
                <label>
                    <input type="checkbox" value="remember-me"> 记住账号
                </label>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
        </form>

    </div> <!-- /container -->
{% endblock body %}

templates/register.html
{% extends "base.html" %}
{% block title %}愿望清单-注册{% endblock title %}
{% load staticfiles %}
{% block topfiles %}
    <script type="text/javascript" src={% static "js/jquery-1.12.4.min.js" %}></script>
    <script type="text/javascript" src={% static "js/register.js" %}></script>
{% endblock topfiles %}

{% block header_con %}
{% endblock header_con %}

{% block body %}

    <div class="container">

        <form class="form-register" method="post">
            {% csrf_token %}
            <h2 class="form-register-heading">注册</h2>
            {{ errmsg }}

            <label for="user_name" class="sr-only">请输入账号</label>
            <input type="text" id="user_name" name="user_name" class="form-control" placeholder="请输入账号" required autofocus>
            <span class="error_tip">提示信息</span>

            <label for="pwd" class="sr-only">请输入密码</label>
            <input type="password" id="pwd" name="pwd" class="form-control" placeholder="请输入密码" required>
            <span class="error_tip">提示信息</span>

            <label for="cpwd" class="sr-only">请输入密码</label>
            <input type="password" id="cpwd" name="cpwd" class="form-control" placeholder="请再次输入密码" required>
            <span class="error_tip">提示信息</span>

            <label for="email" class="sr-only">请输入邮箱</label>
            <input type="email" id="email" name="email" class="form-control" placeholder="请输入邮箱" required>
            <span class="error_tip">提示信息</span>

            <button class="btn btn-lg btn-primary btn-block" type="submit">注册</button>
        </form>
    </div> <!-- /container -->

{% endblock body %}

templates/wish.html
{% extends "base_menu.html" %}

{% block title %}愿望清单{% endblock title %}

{% block right_content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">愿望</h1>

        <h2 class="sub-header">愿望列表</h2>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>愿望</th>
                    <th>许愿人</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>哈哈哈</td>
                    <td>呵呵呵</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock right_content %}